Cookie vs Session vs JWT
java-squid/2022-jubilant pull request #8
Opened 2022-01-30 13:10 UTC by Hyune-c

- 긴가민가 했던 지식을 위주로 정리함.
  - 즉 익히 알려져 있거나, 일반적인 블로그에 정리되어 있는 내용은 가능하면 배제함.

2022-01-31 02:10 UTC, ghojeong requested changes
자세하고 깔끔한 정리 감사합니다! 👍 
특히 중요 포인트들을 굉장히 잘 짚어주셔서, 저도 큰 그림을 그리는데 도움이 되는 것 같습니다. 💯 

궁금한 점들 질문을 드립니다.
그와 동시에, 사소하지만 오타라고 생각되는 부분들 언급해보았습니다.
최소 블로깅, 최대 사내 세미나라고 하셔서 저도 도움이 될 수 있으면 도움이 되고 싶습니다~ 😍

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - 서버가 원할 때 만료시킬 수 있습니다.
Tomcat 에서 발급한 키가, 곧 Redis 의 키가 된다고 이해하면 될까요?
Redis 도 나름 Key-Value DB 로써 자체적인 키 발급 로직이 있을 것 같아서요. 
(하다 못해 AUTO INCREMENT 라던가..)

Tomcat ㅉㅁㄴ에서 키를 발급하는게, Spring 프레임워크 안의 로직 혹은 DB 의 로직보다 더 효율적인 장점 같은게 있는지 궁금합니다.

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 주로 LB 를 사용하여 구현하며 LB 에 부하가 집중되며, 분배 정책에 따라 특정 서버로 트래픽이 집중될 수 있는 단점이 있습니다. (디폴트 정책 - RR)
L7 LB 와 L4 LB 에 관한 설명도 덧붙여 주시면 좋을 것 같습니다.
그리고 RR 은 라운드 로빈 맞나요?

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 세션 복제로 인한 메모리 낭비와 동기화, 락 등의 단점이 있습니다.
세션 동기화를 담당하는 로직이 실행되는 곳은 어디인가요?
각각의 WAS가 모두 동기화 관련 로직을 가지고 있나요?
아니면 동기화 관련 로직을 실행하고 이벤트를 트리거 하는 별도의 머신이 따로 있나요?

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +* 다중 서버 환경에 가장 적절한 방식입니다.
가장 적절한 방식인 이유는 무엇인가요?
Sticky Session 은 부하에 따른 병목 때문에, Session Clustering 은 동기화 때문에 단점이 이해가 가는데,
Session Storage 에 비해서 JWT 가 갖는 장점을 잘 모르겠어서요.
alg 가 base64 처럼 보안에 취약할 경우, Session Storage 가 더 보안에 좋은게 아닌가 하는 생각이 들었습니다.

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - 유일한 방법은 secreat 키 변경 뿐 입니다.
```suggestion
    - 유일한 방법은 secret 키 변경 뿐 입니다.
```

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - secreat key 관리: key rotation, key rolling
```suggestion
    - secret key 관리: key rotation, key rolling
```

제가 잘못 알고 있는 것 같다는생각에 질문드리는데, secreat key 가 올바른 표현인건가요?

2022-01-31 02:10 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +* JWT 구현 샘플 [https://github.com/Hyune-c/common-util](https://github.com/Hyune-c/common-util)
와!!! 샘플까지!!! 짱짱입니다. 👍

2022-01-31 05:57 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +* Connectionless, Stateless 를 지향하는 HTTP 의 단점을 보완하기 위해 사용
- HHTP 는 Connectionless, Stateless 를 지향하다보니 생기는 단점을 보완하기 위해 사용.

모호한 문구를 수정하겠습니다.
---
HTTP 의 단점은 Cookie vs Session vs JWT 가 나온 이유를 생각해보면 알 수 있는데요.
자세한 것은 HTTP 를 주제로 따로 잡는 것이 좋다고 생각하여 단편적인 예만 들겠습니다.

- Connectionless
  - 연결을 위한 핸드쉐이크의 비용이 크다.
    - 보완하기 나온 것이  Keep-alive 헤더.
  - HTTP 2.0 표준까지 보면 좋음.
- Stateless 
  - 업무 요건 만족을 위해 요청에 정보를 넣을 수 밖에 없었다. -> Cookie
  - 쿠키로  하다보니  요청이 커져 네트워크 패킷이 커진다. 그리고 보안의 이슈와 서버 사이드의 컨트롤이 불가능해졌다. -> Session

2022-01-31 05:59 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 주로 LB 를 사용하여 구현하며 LB 에 부하가 집중되며, 분배 정책에 따라 특정 서버로 트래픽이 집중될 수 있는 단점이 있습니다. (디폴트 정책 - RR)
- L7 LB 와 L4 LB 에 관한 설명도 덧붙여 주시면 좋을 것 같습니다.
  - 네트워크 장비에 관련된 설명은 주제 범위를 벗어납니다.
- 그리고 RR 은 라운드 로빈 맞나요?
  - 맞습니다.

2022-01-31 06:06 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - secreat key 관리: key rotation, key rolling
https://datatracker.ietf.org/doc/html/rfc7519

11.  Security Considerations

   All of the security issues that are pertinent to any cryptographic
   application must be addressed by JWT/JWS/JWE/JWK agents.  Among these
   issues are protecting the user's asymmetric private and symmetric
   secret keys and employing countermeasures to various attacks.

> secreat 은 저도 관습적으로 사용한 단어이지만  rfc 에 나와있는 것 같습니다.

![image](https://user-images.githubusercontent.com/55722186/151746421-9418ded5-7d9a-4bcb-8d72-acacf7de893b.png)

> signature 를 만듬에 있어 secreat 만 필요한 줄 알았는데, 본문까지도 포함해서 만드는 거였네요. 
추상화 관점에서는 알 필요가 없는 것이지만 찾은 김에 공유합니다.

---

혹시 secret 가 올바르지 않다고 생각했던 키워드가 있으신가요?

2022-01-31 06:25 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +* 다중 서버 환경에 가장 적절한 방식입니다.
> alg 가 base64 처럼 보안에 취약할 경우, Session Storage 가 더 보안에 좋은게 아닌가 하는 생각이 들었습니다.
- payload 에 민감 정보가 필요한 상황이라면 JWT 를 사용하면 안됩니다.
- 하지만 현대의 개발은 resource 정보에 대해 대리키를 사용하고, 그것의 인가 여부를 토큰으로 판단할 수 있습니다.
- 인가를 위해 사용되는 서버 자원에는 크게 3가지가 있습니다. 
  - 저장 공간 (보통 redis), 서버 자원을 찾기 위한 컴퓨팅, 그리고 보통 언급되지 않지만 저장 공간의 유지 비용 입니다.
  - 상대적으로 session은 저장 공간 큼. 컴퓨팅 낮음. 유지 비용 높음.
  - 상대적으로 jwt 는 저장 공간 낮거나 없음. 컴퓨팅 높음. 유지 비용 낮거나 없음.
  - jwt 의 컴퓨팅 비용이 높다고는 했지만 라이브러리도 있고, 차이는 미미합니다.
  - 반면 session 은 유지 비용에 유실도 포함되어 있고 OPEN API 환경과 같이 트래픽이 늘어나면 늘어날 수록 부담이 터집니다.
- 하지만 JWT 도 단점은 있기에 실무에서는 session + jwt 로 혼용하는 경우도 많습니다.
  - 본문의 `서버에서 강제 만료를 시키기 위해 redis 로 관리하는 방법도 있습니다. session 과의 차이점은 최소 정보만 관리한다는 것입니다.`

2022-01-31 06:27 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 세션 복제로 인한 메모리 낭비와 동기화, 락 등의 단점이 있습니다.
세션 동기화의 역할은 LB 또는 웹서버 입니다.
현대의 개발에서는 웹서버의 역할이 분산되면서 LB 가 합니다.

2022-01-31 06:55 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - 서버가 원할 때 만료시킬 수 있습니다.
JSESSIONID 는 이미 알려진 기술로 spring 을 쓰면 자동 적용되기도 하고, 보안 이슈 등의 옵션도 지원합니다.
따라서 redis 등의 키 발급과 같이 더 효율적인 방법을 찾을 필요는 없습니다.

2022-01-31 09:02 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - 서버가 원할 때 만료시킬 수 있습니다.
오호 관련 지식이 없었는데 알려주셔서 감사합니다!
JSESSIONID 를 키워드로 저도 좀더 공부해봐야겠군요.

2022-01-31 09:02 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 주로 LB 를 사용하여 구현하며 LB 에 부하가 집중되며, 분배 정책에 따라 특정 서버로 트래픽이 집중될 수 있는 단점이 있습니다. (디폴트 정책 - RR)
> 네트워크 장비에 관련된 설명은 주제 범위를 벗어납니다.

앗 그렇네요. 너무 지나쳤습니다.

2022-01-31 09:03 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 세션 복제로 인한 메모리 낭비와 동기화, 락 등의 단점이 있습니다.
오호 그렇군요! LB 가 하는 일이 정말로 많군요.
관련한 실무 경험이 없어서 궁금했는데, 알려주셔서 감사합니다.

2022-01-31 09:04 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +* 다중 서버 환경에 가장 적절한 방식입니다.
session + jwt 를 혼용해서 사용해보지는 못했는데 저도 도전해봐야겠군요.
제가 알고 있던 지식의 틀을 넓혀주셔서 감사합니다.

2022-01-31 09:05 UTC, ghojeong commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - secreat key 관리: key rotation, key rolling
아, 아뇨. secreat 가 반복해서 두번 쓰였길래,
혹시나 정말로 secreat 이라는 용어가 있는지 궁금해서 질문을 드렸습니다.

2022-01-31 09:41 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 세션 복제로 인한 메모리 낭비와 동기화, 락 등의 단점이 있습니다.
- 세션 동기화의 역할은 LB 또는 웹서버 입니다.

다시 읽어보니 조금 이상하게 설명한 거 같네요.

---

- LB 와 웹서버는 JSESSIONID 는 알아도 그에 관련된 정보는 알지 못합니다. 즉 동기화를 시키지는 않습니다.
- `요청이 들어왔던 서버로 연결해주는` staticky session 관점에서의 동기화를 말합니다.
- LB 에서는 이를 기반으로

2022-02-17 11:15 UTC, 102092 commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +## Session
Q1) 쿠키와 세션의 가장 큰 차이점은 무엇일까요?

- https://kim1124.tistory.com/1

2022-02-17 11:19 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +## Session
가장 큰 것을 꼽자면

- cookie 는 매 요청간 데이터가 오감. 보통 민감성 정보를 넣지 않기에 평문으로 사용하지만, 필요한 경우는 암호화나 압축을 하기도 함.
- session 은 데이터는 서버에 있되 그 데이터를 찾기 위한 키 값이 오감.

2022-02-20 10:57 UTC, 102092 approved these changes

2022-02-20 11:20 UTC, ghojeong approved these changes
👍

2022-02-23 14:44 UTC, jypthemiracle approved these changes

2022-02-23 14:44 UTC, jypthemiracle commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - 실무에서는 주로 Redis 를 사용합니다.
왜 Redis를 사용하나요? 다른 In-memory DB도 많을텐데요.

2022-02-23 14:44 UTC, jypthemiracle commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 주로 LB 를 사용하여 구현하며 LB 에 부하가 집중되며, 분배 정책에 따라 특정 서버로 트래픽이 집중될 수 있는 단점이 있습니다. (디폴트 정책 - RR)
그럼 AWS 로드밸런싱에는 Session을 어떻게 관리하나요?

2022-02-23 14:44 UTC, jypthemiracle commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 보통 휘발성의 inmemory DB 인 Redis 를 사용하지만, 필요에 따라 indisk DB 를 사용하기도 합니다.
```필요에 따라```
* 어떤 경우인가요?

2022-02-23 15:04 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +    - 실무에서는 주로 Redis 를 사용합니다.
elastiCahche 도 있는 것 같지만 실무에서 인메모리 db 는 redis 말고 쓰는 것을 본적이 없는 것 같아요.

2022-02-23 15:04 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 주로 LB 를 사용하여 구현하며 LB 에 부하가 집중되며, 분배 정책에 따라 특정 서버로 트래픽이 집중될 수 있는 단점이 있습니다. (디폴트 정책 - RR)
https://linuxer.name/2019/10/alb-sticky-session-%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EC%B0%B0/

수동 구성을 한다면 웹서버에서 설정해줘야 되었던 것이 AWS 를 사용하면 거의 공짜로 됩니다.

2022-02-23 15:04 UTC, Hyune-c commented on Cookie-vs-Session-vs-JWT/dan/README.MD
> +        - 보통 휘발성의 inmemory DB 인 Redis 를 사용하지만, 필요에 따라 indisk DB 를 사용하기도 합니다.
- 비용 절감 or datasource 를 추가로 붙일 수 없는 상황

일반적으로 없는 경우이긴 합니다.
여기서 말하는 indisk DB 는 그냥 mysql 에 테이블을 만들어서 사용한다는 뜻입니다.

2022-02-24 11:25 UTC, merged